
services:
  runner_controller:
    # image: ghcr.io/evolutionary-algorithms-on-click/runner_controller_microservice:main
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      DATABASE_URL : postgresql://root@host.docker.internal:26257/defaultdb?sslmode=disable
      MINIO_ENDPOINT : host.docker.internal:9000
      MINIO_ACCESS_KEY_ID : minioadmin
      MINIO_SECRET_KEY : minioadmin
      RABBITMQ_URL : amqp://user:password@host.docker.internal:5672/
      FRONTEND_URL : http://localhost:3000
      HTTP_PORT : 5002
      AUTH_GRPC_ADDRESS : host.docker.internal:5001